apiVersion: v1
kind: ConfigMap
metadata:
 name: coredns
 namespace: kube-system
data:
 Corefile: |
   .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes a2.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
   }
   a1.local:53 {
       log
       errors
       ready
       cache 10
       forward . 172.18.255.241 {
            force_tcp
       }
   }
