nats:
  advertise: false
  serverNamePrefix: a2-
  extraRoutes:  
  - nats://nats-0.nats.default.svc.a1.local:6222
  jetstream:
    enabled: true
  
auth:
  enabled: true
  basic:
    accounts:
      test:
        users:
        - user: test.form3.tech
      sys: 
        users:
        - user: admin
          password: changeit
  systemAccount: sys

cluster:
  enabled: true
  replicas: 1
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: true
  tls:
    secret:
      name: nats-leaf-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
    
k8sClusterDomain: a2.local

natsbox:
  enabled: false