kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    networking:
      dnsDomain: "ca3.local"
networking:
  disableDefaultCNI: true
  podSubnet: 10.3.0.0/16
  serviceSubnet: 10.20.3.0/24
