nats:
  serverNamePrefix: fps1-
  jetstream:
    enabled: true
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
  
auth:
  enabled: true
  basic:
    accounts:
      ca:
        users:
        - user: ca.form3.tech
        jetstream: true
        imports:
        - stream:
            subject: "FPS.payments"
            account: fps
          prefix: "CA"
      fps:
        users:
        - user: fps.form3.tech
        jetstream: true
        exports:
        - stream: "FPS.payments"
          accounts: 
          - ca
      sys: 
        users:
        - user: admin
          password: changeit
  systemAccount: sys


cluster:
  enabled: true
  replicas: 3
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: true
  remotes:
    - urls:
      - "nats://172.18.255.221:7422"
      - "nats://172.18.255.222:7422"
      account: fps
      tls:
        secret:
          name: fps-user-cert-tls
        ca: "ca.crt"
        cert: "tls.crt"
        key: "tls.key"
  # tls:
  #   secret:
  #     name: nats-leaf-tls
  #   ca: "ca.crt"
  #   cert: "tls.crt"
  #   key: "tls.key"
  #   verifyAndMap: true
    
k8sClusterDomain: fps1.local


natsbox:
  enabled: false
