nats:
  advertise: true
  serverNamePrefix: ca3-
  jetstream:
    enabled: true
    domain: form3
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true

auth:
  enabled: true
  basic:
    accounts:
      ca:
        users:
        - user: ca.form3.tech
        jetstream: true
        imports:
        - stream:
            subject: "FPS.payments"
            account: fps
          prefix: "CA"
      fps:
        users:
        - user: fps.form3.tech
        jetstream: true
        exports:
        - stream: "FPS.payments"
          accounts: 
          - ca
      sys: 
        users:
        - user: admin.form3.tech
  systemAccount: sys


cluster:
  enabled: true
  name: "ca-3"
  replicas: 3
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

gateway:
  enabled: true
  name: "ca-3"
  gateways:
  - name: "ca-2"
    urls:
    - "nats://nats-0.nats.default.svc.ca2.local:7522"
  - name: "ca-1"
    urls:
    - "nats://nats-0.nats.default.svc.ca1.local:7522"
  # tls:
  #   secret:
  #     name: nats-cert-tls
  #   ca: "ca.crt"
  #   cert: "tls.crt"
  #   key: "tls.key"
  #   verify: true
    # verifyAndMap: true

k8sClusterDomain: ca3.local

natsbox:
  enabled: false
