nats:
  advertise: false
  serverNamePrefix: ca2-
  extraRoutes:
  - nats://nats-0.nats.default.svc.ca1.local:6222
  jetstream:
    enabled: true
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true

auth:
  enabled: true
  basic:
    accounts:
      ca:
        users:
        - user: ca.form3.tech
        jetstream: true
        imports:
        - stream:
            subject: "FPS.payments"
            account: fps
          prefix: "CA"
      fps:
        users:
        - user: fps.form3.tech
        jetstream: true
        exports:
        - stream: "FPS.payments"
          accounts: 
          - ca
      sys: 
        users:
        - user: admin
          password: changeit
  systemAccount: sys


cluster:
  enabled: true
  replicas: 2
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: true
  tls:
    secret:
      name: nats-leaf-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
    
k8sClusterDomain: ca2.local

natsbox:
  enabled: false
