nats:
  serverNamePrefix: b1-
  jetstream:
    enabled: true
  
auth:
  enabled: true
  basic:
    accounts:
      test:
        users:
        - user: test.form3.tech
      sys: 
        users:
        - user: admin
          password: changeit
  systemAccount: sys

cluster:
  enabled: true
  replicas: 1
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: true
  remotes:
    - urls:
      - "nats://172.18.255.221:7422"
      - "nats://172.18.255.222:7422"
      account: test
      tls:
        secret:
          name: test-user-cert-tls
        ca: "ca.crt"
        cert: "tls.crt"
        key: "tls.key"
  tls:
    secret:
      name: nats-leaf-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
    
k8sClusterDomain: b1.local


natsbox:
  enabled: false