apiVersion: v1
kind: Service
metadata:
  name: nats-leaf
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
  ports:
  - name: leafnodes
    port: 7422
    protocol: TCP
    targetPort: 7422
  loadBalancerIP: 172.18.255.223
