nats:
  serverNamePrefix: b1-
  jetstream:
    enabled: true
  
auth:
  enabled: true
  basic:
    accounts:
      USERS:
        users:
        - user: a
          password: a
      SYS: 
        users:
        - user: admin
          password: changeit
  systemAccount: SYS

cluster:
  enabled: true
  replicas: 1
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    
k8sClusterDomain: b1.local
