nats:
  advertise: false
  serverNamePrefix: a1-
  extraRoutes:
  - nats://nats-0.nats.default.svc.a2.local:6222
  jetstream:
    enabled: true
  
auth:
  enabled: true
  basic:
    accounts:
      USERS:
        users:
        - user: a
          password: a
      SYS: 
        users:
        - user: admin
          password: changeit
  systemAccount: SYS

cluster:
  enabled: true
  replicas: 2
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: false
  tls:
    secret:
      name: nats-leaf-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    
k8sClusterDomain: a1.local
