apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-user-cert
  namespace: default
spec:
  secretName: test-user-cert-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - form3
    organizationalUnits:
    - paymentservice
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  dnsNames:
  - test
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
