nats:
  advertise: false
  serverNamePrefix: a1-
  extraRoutes:
  - nats://nats-0.nats.default.svc.a2.local:6222
  jetstream:
    enabled: true
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
  
auth:
  enabled: true
  basic:
    accounts:
      test1:
        users:
        - user: test1.form3.tech
        jetstream: true
        imports:
        - stream:
            subject: "TEST2.test"
            account: test2
          prefix: "TEST1"
      test2:
        users:
        - user: test2.form3.tech
        jetstream: true
        exports:
        - stream: "TEST2.test"
          accounts: 
          - test1
      sys: 
        users:
        - user: admin
          password: changeit
  systemAccount: sys

cluster:
  enabled: true
  replicas: 1
  tls:
    secret:
      name: nats-server-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"

leafnodes:
  enabled: true
  noAdvertise: true
  tls:
    secret:
      name: nats-leaf-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
    verifyAndMap: true
    
k8sClusterDomain: a1.local

natsbox:
  enabled: false
